### ISSUE TITLE
custom 

### ISSUE THREAD

**Issue by vil4max** [choefele/CCHMapClusterController#103]
Hi. My name is Maxim, like your implementation, but there was a problem.
I get the data from the server, create an object that is the successor CCHMapClusterAnnotation, transferred to the CCHMapClusterController, but all my data is lost, remain default <MKAnnotation> properties (title, subtitle, coord). My object supports <NSCopyng>. How to create custom CCHMapClusterAnnotation without losing data?
Thanking you in advance.

**Comment by choefele** [comment]
Please have a look at the example project in this repo. There's no need to inherit from `CCHMapClusterAnnotation`. Instead, implement the `MKAnnotation` protocol for your data model object and add an array of these objects to the cluster controller.

**Comment by vil4max** [comment]
Thanks. I will try.

С Уважением,
Вильчевский Maксим

email: vil4max@gmail.com
skype: vil4max

**Comment by choefele** [comment]
Haven't heard back for this issue – I assume it has been solved.
