### ISSUE TITLE
User location with blue pulsating is not showing

### ISSUE THREAD

**Issue by HeenaMulla** [choefele/CCHMapClusterController#104]
Hi I am Heena. I have used this controller to show my custom pins and it is working and looking awesome. Thanks for that. But no wi want to show user location with default blue pulsating dot with userlocation.canShowCallout = NO. I have used mapview.showuserlocation=true. But not working. Please help.

**Comment by choefele** [comment]
Did you [request permission](http://stackoverflow.com/a/25765345) to use the user's location?

**Comment by HeenaMulla** [comment]
Yes I did. I am getting user current location also. It is just it is not added in the array of annotations to pass the controller. I want it to show as default blue pulsating pin on map without any action on it. I am returning nil for viewForAnnotation. When the array is empty user location is showing with blue pin but if not it is not. :(

**Comment by choefele** [comment]
Don't add the user location to the cluster controller – it's handled by the map view. Simply enable it with `showsUserLocation` and ignore it in `mapView:viewForAnnotation:`. This works if you try the example app in this repo (first add code to show permission dialog & enable showsUserLocation, then enable user location in simulator).

**Comment by HeenaMulla** [comment]
In the sample you have given i have tried self.mapview.showUserLocation = True. But its not showing the user location with blue pulsating point. Though I have set location for simulator and also run it on device. I have removed the code for user location in mapView:viewForAnnotation where i was returning nil for it. I am not adding user location to the cluster controller.

**Comment by HeenaMulla** [comment]
Its working. Thanks.
