### ISSUE TITLE
Custom callout view is not hide when tap again

### ISSUE THREAD

**Issue by HTKT** [choefele/CCHMapClusterController#107]
I implement the custom callout view but when i tap on this annotation again, it cannot remove. This is my code so far:

- (void)mapView:(MKMapView *)mapView didSelectAnnotationView:(MKAnnotationView *)view
{
    [mapView deselectAnnotation:view.annotation animated:NO];
    if (![view.annotation isKindOfClass:[MKUserLocation class]])
    {
        BDSCustomInfoWindow *infoWindow = [[[NSBundle mainBundle] loadNibNamed:@"BDSCustomInfoWindow" owner:self options:nil] objectAtIndex:0];
        
        infoWindow.center = CGPointMake(view.bounds.size.width*0.5f, -infoWindow.bounds.size.height*0.5f + 28);
    
        [view addSubview:infoWindow];
    }
}

I already added :  [mapView deselectAnnotation:view.annotation animated:NO]; but still not work. 
Pls. give me advise. Thanks

**Comment by choefele** [comment]
The standard behavior for callouts is that the callout disappears when you tap outside the annotation on the map (this is also how the example in this repo works). If you want a different behavior, I suggest to ask this question on StackOverflow.

**Comment by HTKT** [comment]
Yes thanks. i solved
