### ISSUE TITLE
Add more property (ex: price) in annotation

### ISSUE THREAD

**Issue by HTKT** [choefele/CCHMapClusterController#108]
I want to add 1 more property (ex: Price) in annotation. It will show on the annotation but i dont know how to add. 

- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id<MKAnnotation>)annotation
{
    MKAnnotationView *annotationView;
    
    if ([annotation isKindOfClass:CCHMapClusterAnnotation.class]) {
        static NSString *identifier = @"clusterAnnotation";
        
        HOMPropertyAnnotation *clusterAnnotationView = (HOMPropertyAnnotation *)[mapView dequeueReusableAnnotationViewWithIdentifier:identifier];
        if (clusterAnnotationView) {
            clusterAnnotationView.annotation = annotation;
        } else {
            clusterAnnotationView = [[HOMPropertyAnnotation alloc] initWithAnnotation:annotation reuseIdentifier:identifier];
            clusterAnnotationView.canShowCallout = NO;
        }
        
        CCHMapClusterAnnotation *clusterAnnotation = (CCHMapClusterAnnotation *)annotation;
        clusterAnnotationView.priceValue = @"2.5 Billon";
        clusterAnnotationView.count = clusterAnnotation.annotations.count;
        clusterAnnotationView.blue = (clusterAnnotation.mapClusterController == self.mapClusterControllerRed);
        clusterAnnotationView.uniqueLocation = clusterAnnotation.isUniqueLocation;
        annotationView = clusterAnnotationView;
    }
    
    return annotationView;
}

In above mode, i added clusterAnnotationView.priceValue = @"2.5 Billon" and all annotations always show 2.5 billion. Now i want to change this value corresponding from json data  . Do i need subclass CCHMapClusterAnnotation? Pls. give some advise. Thanks.

**Comment by choefele** [comment]
You have to create a custom class with your property inheriting from `NSObject` that implements `MKAnnotation`. Then, add objects of this class to the cluster controller. [Here is an example](https://github.com/Stolpersteine/stolpersteine-ios/blob/master/Stolpersteine/Shared/Stolpersteine%20API/Stolperstein.h)

**Comment by HTKT** [comment]
Hi guys,

I want to add more attribute in MKAnnotationView not in MKAnnotation. The sample you give is adding to MKAnnotation. That attribute will replace the annotation count attribute. Is it possible ? Thanks

**Comment by choefele** [comment]
Add the additional property to the MKAnnotation. You will always have access to the annotation in the view as well through the `annotation` property.

**Comment by HTKT** [comment]
Thanks. It works great!
But i got a new issue: The price value in Annotation and the price value when click on annotation to show Callout view, they're different. How can I fix this issue? Thanks

**Comment by choefele** [comment]
You probably forgot to implement `mapClusterController:willReuseMapClusterAnnotation`, see [here](https://github.com/Stolpersteine/stolpersteine-ios/blob/master/Stolpersteine/iPhone/MapViewController.m#L271)

**Comment by choefele** [comment]
I assume you have solved your problem because I haven't heard back for a while. Please reopen if needed.

**Comment by happiehappie** [comment]
How do I refer to my custom subclass in viewForAnnotation?
