### ISSUE TITLE
ERROR: Trying to select an annotation which has not been added

### ISSUE THREAD

**Issue by LokeshIB** [choefele/CCHMapClusterController#109]
Error occurred when selecting the button added on the MyCustomCallout then it logs the error on the console and the button action callback doesn't call.
This issue is random but observer frequently.
When user Zoom-In and zoom-out on the map and then open the callout view and selects the button then its works fine.

**Comment by choefele** [comment]
I don't understand the problem you are describing. Can you please provide a sample project that demonstrates this issue.

**Comment by choefele** [comment]
I assume you have solved your problem because I haven't heard back for a while. Please reopen if needed.

**Comment by ruddct** [comment]
Also seeing this on my end, working on repro steps

**Comment by patikzetrixweb1234** [comment]
Trying to select an annotation which has not been added ... sometimes This error when i am click anotationView..i am using delegate method  func mapView(mapView: MKMapView, didSelectAnnotationView view: MKAnnotationView)

**Comment by choefele** [comment]
Please provide a sample project so I can debug this problem

**Comment by anuj-flexsin** [comment]
> Trying to select an annotation which has not been added ... sometimes This error when i am click anotationView..i am using delegate method func mapView(mapView: MKMapView, didSelectAnnotationView view: MKAnnotationView)

Hi,
I am also facing the same issue.
Any updates on this?
Thanks.
