### ISSUE TITLE
Callouts from custom MKAnnotationView

### ISSUE THREAD

**Issue by collabitat** [choefele/CCHMapClusterController#110]
Greetings.  I am trying to use your project and I can get the clustered pins but no longer have any callouts when I tap on them.  I am implementing a custom annotation view via - (CollabitatMapAnnotationView *)mapView:(MKMapView *)mapView
            viewForAnnotation:(id <CollabitatCustomMapItemProtocol>) annotation
Do I need to change something to point to one of your classes?
Thanks much.
William

**Comment by choefele** [comment]
Did you set `canShowCallout ` to `YES`? The example in this repo has an [implementation that works](https://github.com/choefele/CCHMapClusterController/blob/master/CCHMapClusterController%20Example%20iOS/CCHMapClusterController%20Example%20iOS/MapViewController.m#L182).

**Comment by choefele** [comment]
I assume you have solved your problem because I haven't heard back for a while. Please reopen if needed.
