### ISSUE TITLE
First load locations show all in one cluster annotataion

### ISSUE THREAD

**Issue by ALJazeeraIDP** [choefele/CCHMapClusterController#113]
Hi, I am using CCHMapCluster for map related requirements. 
I have an issue, when I first load the screen cluster manager shows all items as well as count of all items which is not correct. See the attached image. 
<img width="1110" alt="screen shot 2015-11-15 at 11 04 13 am" src="https://cloud.githubusercontent.com/assets/8576581/11167911/caa9248a-8b88-11e5-9034-127dc9d3e258.png">

Once I zoom or move the cluster of all annotations count disappears and things get fine. 

It only shows on first launch. Here is the code I am using:

    
    myAnnotation = [[CustomPointAnnotationPin alloc]init];

    
    double lat = [[branch branch_lat] doubleValue];
    double lng = [[branch branch_long] doubleValue];
    
    
    NSLog(@"%f   ---    %f",lat,lng);
    myAnnotation.coordinate = CLLocationCoordinate2DMake(lat, lng);
    myAnnotation.title = [branch branch_title];
    myAnnotation.subtitle = [branch branch_address];
    myAnnotation.vendorID = [branch vendor_id];
    myAnnotation.branchID = [branch branch_id];

    [annotationsArray addObject:myAnnotation];

    [self.mapClusterController addAnnotations:annotationsArray withCompletionHandler:^
     {
         
     }];

**Comment by choefele** [comment]
If you use custom annotations, make sure that you implement both `mapView:viewForAnnotation:` and `mapClusterController:willReuseMapClusterAnnotation:` to always have the annotation view in a consistent state. See [this description](https://github.com/choefele/CCHMapClusterController#custom-annotation-views). The example in this repo also has an implementation of both methods.

**Comment by choefele** [comment]
I haven't heard back in a while so I assume your problem has been solved – thanks
