### ISSUE TITLE
Add extra informations into ClusterAnnotation

### ISSUE THREAD

**Issue by apple80024** [choefele/CCHMapClusterController#114]
Hi, there

Thank you for share this amazing library, it really helps a lot.
How can I add extra information into these clustered annotations which showed on the map view?
I want these annotations could include more then just title, subtitle and coordinate, but also specific image, name, date etc.
And display the image instead on the map view.

Please give me some advises.
Thank you so much.
Brian

**Comment by apple80024** [comment]
I create a  "CustomAnnotation" class and subclass "MKAnnotationView", and include all the informations I need as property in h file. Replace MKPointAnnotation to CustomAnnotation in DataReader.m. Is it good, or need to edit or add something for good?

**Comment by choefele** [comment]
Your approach is correct, except that your custom annotation has to either implement `MKAnnotation` or inherit from `MKPointAnnotation`. (`MKAnnotationView` is used for displaying an annotation.)

**Comment by apple80024** [comment]
Hi, @choefele 

Thank you for your answering, I will try on this.

Also I want to save these extra informations to segue to next view, but I couldn't get them out yet, I segue the data by selected annotation.

I am still working on it, hope I could fix that.
Thank you  so much.
 :)  Brian

**Comment by choefele** [comment]
I haven't heard back in a while so I assume your problem has been solved – thanks

**Comment by happiehappie** [comment]
Can anyone give code example for this? I subclassed MKAnnotation but in my viewForAnnotation, it only takes in CCHMapClusterAnnotation
