### ISSUE TITLE
use Library in swift 2.0 project via cocoapods

### ISSUE THREAD

**Issue by reinholdB** [choefele/CCHMapClusterController#115]
Hi,

How can I use this library in a swift 2.0 project using cocoapods?

I added the following line to my bridging header:
```
#import <CCHMapClusterController/CCHMapClusterController.h>
```
Unfortunately, if I want to use a CCHMapClusterController, the compiler says "unresolved identifier".

Thanks a lot!

**Comment by bbbenja** [comment]
I use this and it works 

```
import CCHMapClusterController
```
