### ISSUE TITLE
Single annotations show cluster-annotation callouts

### ISSUE THREAD

**Issue by xlamquocx** [choefele/CCHMapClusterController#116]
![simulator screen shot nov 20 2015 2 40 51 pm](https://cloud.githubusercontent.com/assets/13092743/11294300/f40a3e4e-8f94-11e5-98d3-a854b9dcc7b4.png)
![simulator screen shot nov 20 2015 1 56 50 pm](https://cloud.githubusercontent.com/assets/13092743/11294301/f85494cc-8f94-11e5-8c61-7595611afe1f.png)

Hi! @choefele,
First word, thank you your framework. It's good framework.
But I have problem with single annotation. I attack my screen shot. Can you check it, please.
Thank you so much, and have a nice day.

**Comment by choefele** [comment]
Sorry, but what is your question exactly?

**Comment by xlamquocx** [comment]
Hi @choefele , My question is:

red pin is single annotation, but show in map is a cluster. You can see it in my picture attack.
Thank for your answer.
![simulator screen shot nov 23 2015 8 39 46 am](https://cloud.githubusercontent.com/assets/13092743/11328505/316db326-91be-11e5-97ef-2c529fb20a0d.png)

**Comment by choefele** [comment]
Two possible reasons for this:
- Two annotations are at the same location – the will count as one location, but you will still have two annotations in `CCHMapClusterAnnotation`'s `annotations`property. You can use the `isUniqueLocation` property to find this out.
- You forgot to implement `mapClusterController:willReuseMapClusterAnnotation:`and update the icon/label of the annotation view

**Comment by xlamquocx** [comment]
Thank for your support, I will try it. Thank you so much

**Comment by choefele** [comment]
I haven't heard back in a while so I assume your problem has been solved – thanks
