### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by SMWARREN** [choefele/CCHMapClusterController#117]
In the Complier I get `Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CCHMapClusterController", referenced from:
      objc-class-ref in MapViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
I receive this error every time I try to include the line self.mapClusterController = [[CCHMapClusterController alloc] initWithMapView:mapView];. I also did some research and found out most of these errors occur because of the architecture but when i changed it to 32 bit i still received the same errors. Can anyone explain whats going on?

**Comment by aoptionu** [comment]
Hi,

What version of the library do you use and how do you integrate it? Can you please provide a sample project that reproduces this problem?

Thanks

**Comment by SMWARREN** [comment]
I followed everything in the Getting Started section on 
https://github.com/choefele/CCHMapClusterController.
I first copied download all of the latest files from the master repo section and dragged the  CCH folder into my project and renamed it cch. Then i linked to the file below. And then in my .m file below. i try to initialize the class.

MapVIewController. H
`#import <UIKit/UIKit.h>
#import <MapKit/MapKit.h>
#import "./cch/CCHMapClusterController.h"
@interface MapViewController : UIViewController<MKMapViewDelegate>
{
    IBOutlet MKMapView  *mapView;
    IBOutlet UIImageView    *imvLine1;
    IBOutlet UIImageView    *imvLine2;
    IBOutlet UIImageView    *imvLine3;
    IBOutlet UIButton       *btToDo;
    IBOutlet UIButton       *btShop;
    IBOutlet UIButton       *btFood;
     NSMutableArray          *lstToDo;
    NSMutableArray          *lstShop;
    NSMutableArray          *lstFood;
}
@property (strong, nonatomic) CCHMapClusterController *mapClusterController;
-(IBAction)btToDoClick:(id)sender;
-(IBAction)btShopClick:(id)sender;
-(IBAction)btFoodClick:(id)sender;
@end`

**MapViewController.M**
`#import "MapViewController.h"
#import "WinnerDetailViewController.h"
#import "AppDelegate.h"
#import "ZSPinAnnotation.h"
#import "ZSAnnotation.h"


@interface MapViewController ()

@end

@implementation MapViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    mapView.delegate = self;
    
    CGRect rt = imvLine1.frame;
    rt.size.width = 0.5f;
    imvLine1.frame = rt;
    
    rt = imvLine2.frame;
    rt.size.width = 0.5f;
    imvLine2.frame = rt;
    
    rt = imvLine3.frame;
    rt.origin.y = 58.5;
    rt.size.height = 0.5f;
    rt.size.width = 320.0f;
    imvLine3.frame = rt;
    
    [btToDo setSelected:YES];
    [btShop setSelected:NO];
    [btFood setSelected:NO];
    
    
    lstToDo = [[NSMutableArray alloc] init];
    lstShop = [[NSMutableArray alloc] init];
    lstFood = [[NSMutableArray alloc] init];
    
    for (int i = 0; i < [[AppDelegate sharedDelegate].lstWinner count]; i++)
    {
        NSDictionary *dictWinner = [[AppDelegate sharedDelegate].lstWinner objectAtIndex:i];
        if ([[dictWinner objectForKey:@"group"] isEqualToString:@"Things To Do"])
        {
            [lstToDo addObject:dictWinner];
        }
        else if ([[dictWinner objectForKey:@"group"] isEqualToString:@"Dining, Food & Lodging"])
        {
            [lstFood addObject:dictWinner];
        }
        else
        {
            [lstShop addObject:dictWinner];
        }
    }
    
    MKCoordinateRegion  region = MKCoordinateRegionMakeWithDistance(CLLocationCoordinate2DMake(41.706738, -70.298364), 30000, 30000);
    [mapView setRegion:[mapView regionThatFits:region] animated:YES];
    
    //self.mapClusterController = [[CCHMapClusterController alloc] initWithMapView:self->mapView];
    //[self.mapClusterController addAnnotations:point withCompletionHandler:NULL];
    [self addPins:0];
    
}

-(void)addPins:(int)index
{
    NSMutableArray *annotationsToRemove = [mapView.annotations mutableCopy];
    [annotationsToRemove removeObject:mapView.userLocation];
    [mapView removeAnnotations:annotationsToRemove];
    
    if (index == 0)
    {
        for (int i = 0; i < [lstToDo count]; i++)
        {
            NSDictionary *dictWinner = [lstToDo objectAtIndex:i];
            ZSAnnotation *point = [[ZSAnnotation alloc] init];
            point.coordinate = CLLocationCoordinate2DMake([[dictWinner objectForKey:@"lat"] floatValue], [[dictWinner objectForKey:@"long"] floatValue]);
            point.title = [NSString stringWithFormat:@"%@, %@",[dictWinner objectForKey:@"name"],[dictWinner objectForKey:@"town"]];
            point.tag = i;
            //self.mapClusterController = [[CCHMapClusterController alloc] initWithMapView:mapView];

            //[self.mapClusterController addAnnotations:point withCompletionHandler:NULL];
            [mapView addAnnotation:point];
        }
    }
    else if (index == 1)
    {
        for (int i = 0; i < [lstShop count]; i++)
        {
            NSDictionary *dictWinner = [lstShop objectAtIndex:i];
            ZSAnnotation *point = [[ZSAnnotation alloc] init];
            point.coordinate = CLLocationCoordinate2DMake([[dictWinner objectForKey:@"lat"] floatValue], [[dictWinner objectForKey:@"long"] floatValue]);
            point.title = [NSString stringWithFormat:@"%@, %@",[dictWinner objectForKey:@"name"],[dictWinner objectForKey:@"town"]];
            point.tag = i;
         //  [self.mapClusterController addAnnotations:point withCompletionHandler:NULL];
             [mapView addAnnotation:point];
        }
    }
    else if (index == 2)
    {
        for (int i = 0; i < [lstFood count]; i++)
        {
            NSDictionary *dictWinner = [lstFood objectAtIndex:i];
            ZSAnnotation *point = [[ZSAnnotation alloc] init];
            point.coordinate = CLLocationCoordinate2DMake([[dictWinner objectForKey:@"lat"] floatValue], [[dictWinner objectForKey:@"long"] floatValue]);
            point.title = [NSString stringWithFormat:@"%@, %@",[dictWinner objectForKey:@"name"],[dictWinner objectForKey:@"town"]];
          
            point.tag = i;
           // [self.mapClusterController addAnnotations:point withCompletionHandler:NULL];
            [mapView addAnnotation:point];
        }
    }

}.......`

**Comment by aoptionu** [comment]
Please follow the instructions for installing this library via CocoaPods and it will take care of the proper setup.

**Comment by SMWARREN** [comment]
I have installed everything with Cocoa Pods but then i am still getting errors
[!] The `BestOfCop [Debug]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `BestOfCop [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `BestOfCop [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `BestOfCop [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

after i put in the $(inherited) flag i only receive the last two error messages instead of 4.

**Comment by choefele** [comment]
These warnings indicate that you have modified your project settings and they clash with the settings that CocoaPods wants to configure.

To make 100% sure there's no problem with `CCHMapClusterController`, I just installed the library via CocoaPods into fresh Xcode project and it worked just fine.

My recommendation would be to create a new Xcode project and start the integration from scratch.

**Comment by SMWARREN** [comment]
After going back in forth between including CocoaPods and not, I have figured out the reference problem it all tied down to adding all the files as a group and not just dragging them into the project as a reference.
