### ISSUE TITLE
How to update the coordinates of annotations.

### ISSUE THREAD

**Issue by skywalker2106** [choefele/CCHMapClusterController#118]
Hi,

I am using the ClusterController for moving vehicles on the map. I would like to animate the coordinate change of the vehicles. Therefore I animate the coordinate property of single annotations with animateWithDuration and update the ClusterController in the completion block with removeAnnotations and addAnnotations for all annotations. This leads to a flicker of the annotations.
Is there an alternative way for updating the coordinates of the annotations?

Many thanks for the help.

**Comment by choefele** [comment]
The annotations are kept in a quad tree based on their coordinate. At the moment, the only way to update these coordinates is to remove the annotation and add it back (this will update the quad tree). 

I'm afraid there's no easy solution to the lack of animations.

**Comment by choefele** [comment]
I'm closing this issue because I haven't heard back in a while – thanks
