### ISSUE TITLE
Issue with annotations without unique location

### ISSUE THREAD

**Issue by ebalassanian** [choefele/CCHMapClusterController#122]
First off, thank you for the excellent work on the library. Much appreciated....

This might be more of a design question. I have an issue where annotations end up having the exact same location. I have coded it so that only unique annotations with a count of 1 show a custom callout view that allows you to open a details page on the item. But when multiple annotations are in the same spot, they show up at grouped and as such, there is no way to view the custom call out. What is the recommended way to handle this? Do I need a new callout that shows a list of the annotations in that point? Or is there a way to somehow show all the annotations in that location (e.g. spread them out).

**Comment by choefele** [comment]
You need to show a list of items in the cluster. In one of my apps, I show a screen with a list and then the user can select the item before ending up on the details page.

**Comment by ebalassanian** [comment]
Thanks. That's what I've done and it worked well.

On Mar 19, 2016, at 7:51 AM, Claus Höfele <notifications@github.com> wrote:

You need to show a list of items in the cluster. In one of my apps, I show
a screen with a list and then the user can select the item before ending up
on the details page.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/choefele/CCHMapClusterController/issues/122#issuecomment-198716458>
