### ISSUE TITLE
Can't disable clustering for annotations with same coordinates.

### ISSUE THREAD

**Issue by bhapca** [choefele/CCHMapClusterController#124]
The current API has (at least) 2 ways of disabling the clustering:
* `/** The maximum zoom level before clustering will be disabled and each annotation on the map will
 have a unique location (default: `DBL_MAX`). */`

`@property (nonatomic) double maxZoomLevelForClustering;`

* `/** The minimum number of unique locations before a cell gets clustered (default: 0). */`

`@property (nonatomic) NSUInteger minUniqueLocationsForClustering;`

However, If I try to run a simple test, as that from https://github.com/bhapca/CCHMapClusterController/commit/892be49213ec1039638e032f8781edc05f8a2d5b, I still get a cluster (with a single annotation view) as shown below:

![simulator screen shot 31 may 2016 17 13 36](https://cloud.githubusercontent.com/assets/7116742/15678943/c0d23ade-2758-11e6-9e41-bc69a9934009.png)

What I would have expected is 2 different annotation views, overlapping, like so:
![simulator screen shot 31 may 2016 17 27 39](https://cloud.githubusercontent.com/assets/7116742/15679029/07bb98be-2759-11e6-9c85-9be24c1f239a.png)
![simulator screen shot 31 may 2016 17 27 41](https://cloud.githubusercontent.com/assets/7116742/15679039/0de9014a-2759-11e6-86e2-c12cea9771a4.png)

I believe the same issue was flagged by https://github.com/Tron5000/CCHMapClusterController/commit/9e6cbac31cb2b244f1a17877ccbea05f9bea5ff0.

**Comment by choefele** [comment]
Thanks for your feedback. Annotations at the same location are always clustered. This is by design because annotations couldn't be selected otherwise because they overlap. You can still decide in your app hpw you visually represent these annotations.

**Comment by bhapca** [comment]
Claus,

Thanks for the quick reply. 

Overlapping annotations could be selected programatically. There’s a public API that allows us to do so. Also, in the sample app I mentioned above, if I tap on overlapping annotations the selection switches from one to another. So, there are ways to select overlapping annotations.

My scenario is as follows: When the user taps on a cluster it “explodes" into individual pins, of which one is selected, and a card showing its corresponding details is shown at the bottom of the screen, the map remaining still partially visible. If the user swipes the card to a new one, its corresponding pin should be selected on the map. 

Right now there’s no way to fully “explode" a cluster that has annotations at the same location. Having a special visual representation for a cluster with overlapping annotations, to “fake" the image of a single pin, is an option, albeit a cumbersome one, because in my case that image has to change based on the selected annotation. I guess I’ll have to not use CCHMapClusterController in that “exploded" mode.

**Comment by aoptionu** [comment]
Even if the cluster consists of annotations at the same location, you can still explode those annotations visually. Would that work?

> Am 01.06.2016 um 21:39 schrieb bhapca <notifications@github.com>:
> 
> Claus,
> 
> Thanks for the quick reply. 
> 
> Overlapping annotations could be selected programatically. There’s a public API that allows us to do so. Also, in the sample app I mentioned above, if I tap on overlapping annotations the selection switches from one to another. So, there are ways to select overlapping annotations.
> 
> My scenario is as follows: When the user taps on a cluster it “explodes" into individual pins, of which one is selected, and a card showing its corresponding details is shown at the bottom of the screen, the map remaining still partially visible. If the user swipes the card to a new one, its corresponding pin should be selected on the map. 
> 
> Right now there’s no way to fully “explode" a cluster that has annotations at the same location. Having a special visual representation for a cluster with overlapping annotations, to “fake" the image of a single pin, is an option, albeit a cumbersome one, because in my case that image has to change based on the selected annotation. I guess I’ll have to not use CCHMapClusterController in that “exploded" mode.
>

**Comment by bhapca** [comment]
@aoptionu, yes, I suppose it's possible to manipulate the annotation view of the cluster with annotations at the same location, to give it any visual appearance desired. Thanks !
