### ISSUE TITLE
Cluster view with only 1 annotation when using reuseExistingClusterAnnotations=true

### ISSUE THREAD

**Issue by mtaweel** [choefele/CCHMapClusterController#128]
First of all, great library :)

When i'm using reuseExistingClusterAnnotations=true, and after zooming into a cluster with lets say 3 annotations (count = 3), the cluster gets split correctly for two annotations but one annotation stays in the ClusterView with count one.

<img width="258" alt="screen shot 2016-08-16 at 5 41 24 pm" src="https://cloud.githubusercontent.com/assets/11316554/17703169/69d62174-63d9-11e6-9a99-b61c8cdcd225.png">

I'm implementing willReuseMapClusterAnnotation and updating the count correctly, but when debugging this, I can see it's being called to reuse the cluster view for count of 1 even that i'm setting minUniqueLocationsForClustering = 3

However, this issue disappears if I set reuseExistingClusterAnnotations=false, but I get the nasty flickering annotation-views when dragging and moving around the map.

Can you please help sorting out this issue

**Comment by choefele** [comment]
To handle this correctly in `willReuseMapClusterAnnotation`, you need to write your custom annotation view to adapt to both cases (being a cluster or being a unique annotation). In the example, this handled [here](https://github.com/choefele/CCHMapClusterController/blob/master/CCHMapClusterController%20Example%20iOS/CCHMapClusterController%20Example%20iOS/MapViewController.m#L164)

**Comment by mtaweel** [comment]
Thanks! Indeed, I was using two different custom annotation views, one for cluster and one for single annotation. Now I fixed it, I used only one custom annotation view and i hide/show inner views based on `isUniqueLocation()`.

Thank you very much
