### ISSUE TITLE
Annotation views occasionally disappear while panning/zooming

### ISSUE THREAD

**Issue by ts95** [choefele/CCHMapClusterController#129]
I've made a video to illustrate the issue https://youtu.be/DznTUXs1d-s

**Comment by choefele** [comment]
Have you implemented both `mapView:viewForAnnotation:` and `mapClusterController:willReuseMapClusterAnnotation:` as detailed [here](https://github.com/choefele/CCHMapClusterController#custom-annotation-views)? Maybe you could try out the project in this repo to see a working example

**Comment by choefele** [comment]
I haven't heard back in a while – I assume this issue has been resolved, thanks
