### ISSUE TITLE
Two markers at exact same location

### ISSUE THREAD

**Issue by georgij** [choefele/CCHMapClusterController#134]
If I have two markers at exact same location the library cluster them no matter what the other settings are (like maxZoomLevelForClustering or minUniqueLocationsForClustering). Then even if you click it and zoom in until the max possible level they stay clustered. Is it possible to prevent/disable this?

**Comment by choefele** [comment]
You can't disable this – in my opinion, this makes sense because two annotations views at the exact same spot wouldn't be selectable/visible
