### ISSUE TITLE
How to get the instance of CCHMapClusterAnnotation?

### ISSUE THREAD

**Issue by ram2386** [choefele/CCHMapClusterController#135]
Thanks for sharing the repository with us.

As I am currently working on track the pin same as Uber type application, so for that I need the particular instance of CCHMapClusterAnnotation to update the pin like change the latitude/longitude and refresh the map.

Thanks in advance.

**Comment by choefele** [comment]
The original annotations that you added to the controller are stored inside the `annotations` property. Currently, changing the the lat/long of these annotations won't updated the map – you will need to remove and re-add annotations.

**Comment by ram2386** [comment]
So you are saying that if I have to update or movement the existing pin same like uber application then I have to remove and re-add pin.

**Comment by aoptionu** [comment]
Yes

**Comment by ram2386** [comment]
Thanks for the reply and good work. And if you want then you can close these issue.
