### ISSUE TITLE
Crash due to usage of KVO

### ISSUE THREAD

**Issue by albertodebortoli** [choefele/CCHMapClusterController#136]
Users of my app are encountering the following crash in production, which I'm not able to reproduce locally.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fb1db06be30 of class MKMapView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x60000023d560> (
<NSKeyValueObservance 0x60000044ae30: Observer: 0x60000023d820, Key path: delegate, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000251ee0>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ebfad4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010e65c21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ec642b5 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000109e61ba1 NSKVODeallocate + 293
	4   libobjc.A.dylib                     0x000000010e6711d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	5   CoreFoundation                      0x000000010eb47676 _CFAutoreleasePoolPop + 22
	6   CoreFoundation                      0x000000010eb84385 __CFRunLoopRun + 2213
	7   CoreFoundation                      0x000000010eb83884 CFRunLoopRunSpecific + 420
	8   GraphicsServices                    0x0000000111ad5a6f GSEventRunModal + 161
	9   UIKit                               0x000000010bd54c68 UIApplicationMain + 159
	10  MYAPP                             0x00000001034405e2 main + 770
	11  libdyld.dylib                       0x000000010fb2e68d start + 1
	12  ???                                 0x0000000000000003 0x0 + 3
)
```

It surely is related to some magic done in `CCHMapViewDelegateProxy` when adding and remove the observer for the "delegate' keyPath.

**Comment by choefele** [comment]
Mmmh, without a way to reproduce this issue, it's going to be difficult to fix. Maybe you are using an unusual way of initializing/destroying the map view?

**Comment by albertodebortoli** [comment]
You're indeed right, I tried everything but couldn't reproduce. It happens on all devices/OS. This is how I allocate it:

```
self.mapClusterController = [[CCHMapClusterController alloc] initWithMapView:self.mapView];
self.mapClusterController.delegate = self;
self.mapClusterController.cellSize = 60.0f;
self.mapClusterController.minUniqueLocationsForClustering = 5;
self.mapClusterController.maxZoomLevelForClustering = 15.5f;
```

I appreciate it'll be hard to figure this out, thought it was worth to open the issue though.

**Comment by bordoli** [comment]
Hi, 
same issue described by Alberto appears
"An instance 0x17285e00 of class MKMapView was deallocated while key value observers were still registered with it. Current observation info: _NSKeyValueObservationInfo 0x16f1db30_ (_NSKeyValueObservance 0xb14a5b0: Observer: 0x16f2ff60, Key path: delegate, Options: _New: YES, Old: NO, Prior: NO_ Context: 0x0, Property: 0xb14a5d0_)"
Also from my side, only users are encountering it.
From description seems that "mapView" property of CCHMapViewDelegateProxy is deallocated while an instance of CCHMapViewDelegateProxy is still observing it.

It will be great if you can have a look.

**Comment by LivioGama** [comment]
Same here. I was never able to reproduce it myself though.
![capture d ecran 2017-11-29 a 10 55 51](https://user-images.githubusercontent.com/6930498/33369141-f0b3abb2-d4f3-11e7-962c-4b9ad213f6e1.png)
