### ISSUE TITLE
Can't see annotation while too zoomed out

### ISSUE THREAD

**Issue by happiehappie** [choefele/CCHMapClusterController#140]
I try to refresh my view when my zoom level changes too much, cause zooming out I should show more annotations with a different radius.
However, zooming out too much makes all my annotations disappear, I print my count of self.mapClousterController.annotations.count and they return 17.

**Comment by happiehappie** [comment]
Apparently it only happens when I add after remove. I tried commenting out the line with removeannotations things are as expected

**Comment by choefele** [comment]
Can you reproduce the same issue in the example app? You'll probably need to implement the completion handler in `addAnnotations:annotations withCompletionHandler:` and remove in there to avoid messing up the annotations

**Comment by happiehappie** [comment]
Hmm, I tried replicating that in the example app but I failed apparently. But to continue with your advice. 

> You'll probably need to implement the completion handler in addAnnotations:annotations withCompletionHandler: and remove in there to avoid messing up the annotations

Why am I removing my annotations in the addAnnotations completion block?

Currently this is how I do it.

`                self.mapClusterController.removeAnnotations(Array(self.mapClusterController.annotations), withCompletionHandler: {
                    self.mapClusterController.addAnnotations(self.locations, withCompletionHandler: nil)
                    
                })`

**Comment by choefele** [comment]
I haven't heard back from this issue in a while, so I'm closing it for now. Let me know if you have more issues – thanks
