### ISSUE TITLE
Annotation coordinate is not properly updated

### ISSUE THREAD

**Issue by nderkach** [choefele/CCHMapClusterController#141]
When I change MKAnnotation's `coordinate` property for any of annotations in a cluster, annotation location is not updated, unless I pan the map which supposedly trigger annotation redraw.

This appears to be a bug related to `CCHMapClusterController`, as I'm able to manipulate coordinates of the same annotations outside the cluster (i.e. the ones directly added to MKMapView).

**Comment by choefele** [comment]
Sorry, but changing the coordinates while being clustered is not supported. You'll have to remove and re-add the annotation

**Comment by choefele** [comment]
I haven't heard back from this issue in a while, so I'm closing it for now. Let me know if you have more issues – thanks
