### ISSUE TITLE
Displaying different annotation views

### ISSUE THREAD

**Issue by pkuklis** [choefele/CCHMapClusterController#142]
Hi,

I'd like to display multiple kinds of annotation views (e.g. "Location Annotation", "Location Cluster", "Event Annotation", "Event Cluster") using CCHMapClusterController. 

What's the best way to implement this? Should I use multiple cluster controllers or is it possible with one?

**Comment by choefele** [comment]
You can register multiple subclasses of `MKAnnotation` on the same cluster controller, but they will be cluster together. If you want to cluster each type of annotation separately, you'll need to use multiple cluster controllers
