### ISSUE TITLE
Make the representation of ClusterAnnotationView unchanged when zooming in or out

### ISSUE THREAD

**Issue by maplestory06** [choefele/CCHMapClusterController#143]
Thank you for this repo, great help!

In each square cell on map, I select one annotation to represent this square area. 
To represent the exact coordinate of this annotation, I use CCHNearCenterMapClusterer.

However, when I zoom in or out the map, the annotationView is reused, the image is changed to another annotation's. But the clusterAnnotation's coordinate is not changed.
My goal is to keep the representation of the clusterAnnotationView unchanged.
I believe this is because I implement viewForAnnotation and willReuseMapClusterAnnotation and always return the very first annotation of the annotations in the clusterAnnotation.

How can keep the image unchanged while keep the data unchanged, too?
To keep image unchanged is easy, just ignore the willReuseMapClusterAnnotation method, but when I tap on that map, the data is no longer the same as what the image of this annotation's.

Please help. 😭

**Comment by maplestory06** [comment]
And I know that the ReadMe file has description for this situation, but I opened this issue to see if repo owner or someone could offer help on this.

Thanks in advance!

**Comment by choefele** [comment]
Hi – to properly handle annotations, you have to implement both `viewForAnnotation` and `willReuseMapClusterAnnotation`. [This view controller](https://github.com/Stolpersteine/stolpersteine-ios/blob/master/Stolpersteine/iPhone/MapViewController.m) is an example on how to do this.

Hope this helps
-Claus

**Comment by maplestory06** [comment]
Hi, Claus, thank you for quick response!

I think I have well acknowledged this kind of mechanism in your framework.
I mean the use of both viewForAnnotation and willReuseMapClusterAnnotation.

My app is not using this framework to show the number of annotations in a clusterAnnotationView on map. My app is to choose one of these annotations as the representative for the cluster.

But I encountered like two desired goals:

1. When I select a annotationView, I want to make this annotationView always above all annotationView, no matter how I zoom in or out the mapView.
(For now, this selected one is clustered when the mapView is zoomed in or out)

2. (I implemented both viewForAnnotation and willReuseMapClusterAnnotation to make data consistent) When I slightly changed the zoom level, two nearby clusters will be re-clustered, and the annotations of these two clustered may be allocated to different clusterAnnotation. So the representative for this cluster is changed (due to the use of willReuseMapClusterAnnotation), but because of the both QuadTree data structure and willReuseMapClusterAnnotation method, the coordinate of the annotationView is not changed. Is there any way to solve this one? I know I can delete from QuadTree and re-add into it, but if I do so in willReuseMapClusterAnnotation, the map will keep refreshing and the animation will be called many many times than the usual.

3. (This is a Question) when I turned off the "reuseExistingClusterAnnotations", the map is keep refreshing (animation of huge amount of annotationViews like newly added to clusterManager), why would this happen?

Thank you, Claus
Joshua

**Comment by choefele** [comment]
For 1.), if I understand correctly, you want to keep an annotation view selected when zooming in and out. Does `selectAnnotation:andZoomToRegionWithLatitudinalMeters:` help? This will find the annotation in the clustered annotation views. You'd have to find the annotation again and re-select it after the users has finished zooming the map

**Comment by maplestory06** [comment]
I'll temporarily close this issue, though it is not resolved. 

Thanks again for your help!
