### ISSUE TITLE
Removing Annotations doesn't work correctly

### ISSUE THREAD

**Issue by edwardmp** [choefele/CCHMapClusterController#149]
Hi,

I just tried this library as a replacement for MapKit clustering, as there are several severe bugs in MapKit clustering.. so libraries such as this are still quite useful.

However, I noticed some issues in using this library as well. Eventually I tracked this down to the fact that the annotations are never removed when I call `removeAnnotations` on the clustermanager. I logged the count of number of annotations before and after the remove operation and it keeps increasing.

Some context: I frequently fetch a list of locations from a server, then remove all existing annotations, and add the updated list of locations to the map.

Should `self.mapClusterController.removeAnnotations(self.mapView.annotations)`  work?
And should I only add new annotations when the completionhandler of removeAnnotations is called?

**Comment by choefele** [comment]
You need to use the annotation objects that you added with `mapClusterController.addAnnotations` (don't use the annotations from your map view – they are different)

**Comment by edwardmp** [comment]
@choefele 
is there an easy way to get all existing annotations from the mapClusterController?

**Comment by edwardmp** [comment]
@choefele 

thanks. Got it to work now. Only issue is that `annotations` is a set that doesn't specify a datatype, which makes working with it in Swift a bit harder.

Also I get a bunch of `Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior` warnings. Do you accept a PR fixing this?

**Comment by choefele** [comment]
Yes, will have a look

**Comment by choefele** [comment]
Published 1.7.2 – thanks
