### ISSUE TITLE
Disable Clustering if the Map is zoomed all the way in

### ISSUE THREAD

**Issue by onato** [choefele/CCHMapClusterController#4]
If the map is zoomed all the way in, some annotations are still clustered and are thereby inaccessible. 

Clusters should only be shown if it is still possible to zoom in.

**Comment by eimantas** [comment]
Which one of these features take precedence? Now I have both set: `minUniqueLocationsForClustering` as well as `maxZoomLevelForClustering` and I still always see cluster annotations.

**Comment by choefele** [comment]
If one or the other condition is true, clustering is disabled. Note that this only affects annotations that are in distinct locations. Annotations in the same location are still clustered.

**Comment by markkrenek** [comment]
What determines "same location"?

**Comment by choefele** [comment]
This is determined by comparing a [geo hash](https://en.wikipedia.org/wiki/Geohash) of two locations. The implementation is [here](https://github.com/choefele/CCHMapClusterController/blob/master/CCHMapClusterController/CCHMapClusterControllerUtils.m#L310). It's basically making sure two locations are very close.
