### ISSUE TITLE
Crash: [__NSPlaceholderSet initWithObjects:count:]: attempt to insert nil

### ISSUE THREAD

**Issue by alxon** [choefele/CCHMapClusterController#41]
Hello

This is the case when the data is already loaded completely and the user quickly switches to map portions of coordinates. For example, the countries

How to reproduce:
1 "CCHMapClusterController Example iOS" - DataReader.m
method "dispatchAnnotations" - comment out "[NSThread sleepForTimeInterval: DELAY_BETWEEN_BATCHES]"
2 frequently and quickly press the "reset"

CCHMapClusterController Example iOS[4322:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderSet initWithObjects:count:]: attempt to insert nil object from objects[9972]'

sometimes falls out of memory

**Comment by zulkis** [comment]
Keeps happening since fixes of #62, commit 5681ea9c92d0b2ae972dd83f1d4b2ff2e3dea90d

**Comment by choefele** [comment]
@zulkis Do you have a test case that I van use to reproduce this issue?

**Comment by zulkis** [comment]
Wanted I say yes, but it just happened twice while replacing annotations 
and tapping on one of them to select.

**Comment by choefele** [comment]
I don't see how this is possible because the `allAnnotations` property in `CCHMapClusterController` is only ever used on the main thread. 

Can you please double-check that you are calling `annotations`, `addAnnotations:withCompletionHandler:` and `removeAnnotations:withCompletionHandler:` on the main thread?

Also, could you provide a crash log.

Thanks

**Comment by zulkis** [comment]
I understand it about mainThread.

Yes, in my case the always called in mainThread.

https://gist.github.com/zulkis/548666137fcae5968c59

**Comment by choefele** [comment]
The crash is happening inside an `NSBlockOperation` on a background thread that calls `[CCHMapClusterController annotations]`. This is not allowed. You have to make sure that accessing the `annotations` property only ever happens on the main thread.

**Comment by zulkis** [comment]
Oh, i just discovered that I have `NSOperationQueue` over multiple cluster controllers... And actually it uses first thread available. So it could possible lead us to execute my operations in background. Shit.

Thank you sir.

**Comment by choefele** [comment]
Your are welcome :-)
