### ISSUE TITLE
Type casting ??

### ISSUE THREAD

**Issue by ilkererdemsen** [choefele/CCHMapClusterController#52]
Hi 
Type casting not working in my code. 
- (void)mapClusterController:(CCHMapClusterController *)mapClusterController willReuseMapClusterAnnotation:(CCHMapClusterAnnotation *)mapClusterAnnotation
  {
  ClusterAnnotationView *clusterAnnotationView = (ClusterAnnotationView *)[self.mapView viewForAnnotation:mapClusterAnnotation];
  clusterAnnotationView.count = mapClusterAnnotation.annotations.count;
  clusterAnnotationView.uniqueLocation = mapClusterAnnotation.isUniqueLocation;
  }

clusterAnnotationView is already MkpinAnnotation object. So give "[MKPinAnnotationView setCount:]: unrecognized selector sent to instance" error.

What should I do??

Thanks

**Comment by matrosovDev** [comment]
Yep seems like there are no delegate for mapview. Use suleymanccelik answer to resolve this issue. It works for me as well. In the example project delegate set via storyboard and when you copied just controllers and other files but not storyboard. You will get this problem. So just assign delegate to your map view and everything will work correct. Thanks to suleymanccelik!
