### ISSUE TITLE
Remove all annotations not working properly

### ISSUE THREAD

**Issue by bilby91** [choefele/CCHMapClusterController#54]
Hello guys,

I'm having some trouble using `removeAnnotations:withCompletionHandler` when updating my annotations after adding them to the map.

The problem is that after updating the coordinate of my annotations, some of them are never removed from the map. From what I found ( guess ), `CCHMapTreeNodeRemoveData(_root, data))` is in charge of removing the node from the map, internally it calls `CCHMapTreeBoundingBoxContainsData` to see if the data is inside the bounding box of the node. I thinks the problem here is that the bounding box of the tree is outdated due to the update in the coordinate.

I'm using Core Data with my application for backing up my annotations. Map Kit uses KVO to observe the coordinate property of the annotation and update the position if it changes, I think CCHMapClusterController doesn't have the same behaviour. 

Let me know if anything of what I said makes sense.

Thanks and keep up the good work.

**Comment by kirandb** [comment]
Hi I am having this issue in deleting the current annotations while reloading the data . Could you please update with the ideal way to reset the map , clear QuadTree  ?

**Comment by choefele** [comment]
Removing data should work if you make sure to chain all calls using the completion blocks: first call `)removeAnnotations:withCompletionHandler:` and then in this method's completion handler add new annotations.

**Comment by uknowmeright** [comment]
This is still an issue. I cannot seem to get rid of old annotations when I load new data. I have tried:

`        mapView.removeAnnotations(mapView.annotations)
        mapClusterController.removeAnnotations(mapView.annotations) { () -> Void in
            //main thread?
            dispatch_async(dispatch_get_main_queue()) {
                self.mapView.setNeedsDisplay()
                self.mapView.reloadInputViews()
                
                for listing in AppDataInstance.listingResults[self.dataStream].listings{
                    // Drop pins
                    self.dropPinForListing(listing)
                }
            }
        }`

But it does not seem to work. Any Ideas?
