### ISSUE TITLE
Issues in: Zooming in to a cluster + Centering the map without changing the zoom level

### ISSUE THREAD

**Issue by inal** [choefele/CCHMapClusterController#59]
Hi,

I am facing 2 issues which are mentioned below:
1. While using the code to "Centring the map without changing the zoom level"
   which is as below:
   MKMapPoint point = MKMapPointForCoordinate(view.annotation.coordinate);
   MKMapRect rect = [mapView visibleMapRect];
   rect.origin.x = point.x - rect.size.width \* 0.5;
   rect.origin.y = point.y - rect.size.height \* 0.5;
   [mapView setVisibleMapRect:rect animated:YES];

Map view zooms out [earlier zoom level is around 17 and after running above lines of code zoom level is 16], due to which the annotations are clustered again and "didDeselectAnnotationView" is called. Due to this, user is never able to view these annotations, every-time the view is zoomed out. If user try to manually zoom in again, then again the view is zoomed out.
1. While using the code to "Zooming in to a cluster"
   using these lines of code:
   if ([view.annotation isKindOfClass:CCHMapClusterAnnotation.class]) {
       CCHMapClusterAnnotation *clusterAnnotation = (CCHMapClusterAnnotation *)view.annotation;
       MKMapRect mapRect = [clusterAnnotation mapRect];
       UIEdgeInsets edgeInsets = UIEdgeInsetsMake(20, 20, 20, 20);
       [mapView setVisibleMapRect:mapRect edgePadding:edgeInsets animated:YES];
   }

It works perfectly till zoom level reached around 17, but after that i again want to zoom further, need zoom level of 18.5 approx., but it does not allow to zoom. Rather, it keeps on showing the same location again and again.

My need is that, if the annotation is clustered, then zoom further till one unique location is found. And once that unique location is found, show the annotation view. 

Sample code is here (includes the code for both the above mentioned issues):
- (void)mapView:(MKMapView *)mapView didSelectAnnotationView:(ClusterAnnotationView *)view {
  
  if ([view.annotation isKindOfClass:[MKUserLocation class]]) {
  }
  else{
  
  ```
  CCHMapClusterAnnotation *clusterAnnotation = view.annotation;
  
  if (clusterAnnotation.isUniqueLocation == FALSE){
      CCHMapClusterAnnotation *clusterAnnotation = (CCHMapClusterAnnotation *)view.annotation;
      MKMapRect mapRect = [clusterAnnotation mapRect];
       CGFloat val = 10;
      UIEdgeInsets edgeInsets = UIEdgeInsetsMake(val, val, val, val);
      [mapView setVisibleMapRect:mapRect edgePadding:edgeInsets animated:YES];
  }
  else{
      // mapView.centerCoordinate = view.annotation.coordinate;
      MKMapPoint point = MKMapPointForCoordinate(view.annotation.coordinate);
      MKMapRect rect = [mapView visibleMapRect];
      rect.origin.x = point.x - rect.size.width * 0.5;
      rect.origin.y = point.y - rect.size.height * 0.5;
      [mapView setVisibleMapRect:rect animated:YES];
  
    [customCalloutView setTag:kTag_CustomCalloutView];
      [view addSubview:customCalloutView];
  
     [customCalloutView setCenter:CGPointMake(view.bounds.size.width * 0.5f, -customCalloutView.frame.size.height * 0.5f)];
  
      NSArray *myArray = [clusterAnnotation.annotations allObjects];   
  
      NSMutableArray *tempArr = [[NSMutableArray alloc] init];           
  
      for (int _i = 0; _i < [myArray count]; _i++){                
          CustomPointAnnotation *pointAnnotation = [myArray objectAtIndex:_i];
  
          [tempArr addObject:searchResultsArray[pointAnnotation.tag]];
  
      }            
      annotationzArray = nil;
      annotationzArray = tempArr;
      [annotationzTV reloadData];
  }
  ```
  
  }
  }

Please respond asap.

Thanks in advance!

**Comment by ayalcinkaya** [comment]
what is the solution ?
