### ISSUE TITLE
Annotation views are not relocated when annotation coordinate is changed

### ISSUE THREAD

**Issue by grigorye** [choefele/CCHMapClusterController#64]
Annotation views are not relocated when annotation coordinate is changed. Apparently that's missing functionality versus MKMapView. I need to update .coordinate of some of my annotations, and the update is not reflected on the map if the annotations were added via cluster controller - I'm sure that .coordinate property is not even observed in such a case. If I switch to plain MKMapView, it works as expected: annotation views are (automatically) moved when I change .coordinate of annotations.

**Comment by choefele** [comment]
Closing this for now. Please reopen if there are new ideas on how to implement this. Thanks
