### ISSUE TITLE
How to pass the id of an MKAnnotation via a segue to the next ViewController

### ISSUE THREAD

**Issue by daclarus** [choefele/CCHMapClusterController#69]
Hi,

I do have a question about how to find out which MKAnnotation is the current selected:

First of all: I do use CCHMapClusterController in a Swift Project. The Clustered Map does work perfect. My plan is to show some more details when the user does click on the rightCallout Button. Making the AnnotationView show up, clicking rightCalloutButton und do a segue to a DetailView does work fine. Except for a big problem: How do I find out which Annotation was clicked an which details shoud be shown?

My idea is to pass an id (or uuid) to the DetailViewController via the segue. But how do I find out the corret id (or uuid) to pass?

I've created this swift class:

    class BoothAnnotationLocation: NSObject, MKAnnotation
    {
        var coordinate: CLLocationCoordinate2D
        var title: String
        var subtitle: String
        var uuid: String
        
        init(coordinate: CLLocationCoordinate2D, title: String, subtitle: String, uuid: String) {
            self.coordinate = coordinate
            self.title = title
            self.subtitle = subtitle
            self.uuid = uuid
        }  
    }

I do put all annotations to a big array and add this to the cluster controller

    var BoothAnnotationLocationList = [BoothAnnotationLocation]()
    ...
    var a = BoothAnnotationLocation(coordinate: vendorLocationNew, title: supTitle!, subtitle: supSubtitle!, uuid: supUUID!)
    self.BoothAnnotationLocationList.append(a)
    ...
    self.mapClusterController.addAnnotations(self.BoothAnnotationLocationList,    withCompletionHandler: nil)

-> The Map does show up and is clustered

I've implemented 

    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject!) {
            if segue.identifier == "showBoothLocationDetail" {
            
                let annotation = sender.annotation as MKAnnotation
                NSLog(annotation.title!)
                
               ...
           
           
But in prepareForSegue I can only get access to an MKAnnotation Object which does not hold the needed id/uuid to pass it to the DetailViewController via a segue? 

Is there any reliable path to receive the id/uuid to pass it to the next ViewController?

**Comment by choefele** [comment]
The map view has a selected annotation, which will be of the type `CCHMapClusterAnnotation` and you can get the annotations in the cluster from the `annotations` property. 

You'll have to deal with the fact that there might one or more annotations clustered, e.g. by showing the detail screen in the first case and a list in the second.

Maybe [this code helps](https://github.com/optionu/stolpersteine-ios/blob/master/Stolpersteine/iPhone/MapViewController.m#L183)? In this app, I'm calling `performSegueWithIdentifier:sender:` from within `mapView:annotationView:calloutAccessoryControlTapped:`.

**Comment by daclarus** [comment]
Hi Claus,

thanks a lot for your answer! Unfortunately I'm still confused. 

Referring to your "this code helps?" I tried this:

        override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject!) {
        if segue.identifier == "showBoothLocationDetail" {
            
            var selectedAnnotation: MKAnnotation = self.MapSearchBooth.selectedAnnotations[0] as MKAnnotation
            NSLog("selectedAnnotation.title!")
            NSLog(selectedAnnotation.subtitle!)
            
            let mapClusterAnnotation: CCHMapClusterAnnotation = selectedAnnotation as CCHMapClusterAnnotation
            NSLog(mapClusterAnnotation.title)
            NSLog(mapClusterAnnotation.subtitle)

In both NSLog sections I do recieve title and subtitle of the selected annotation. 

But I still don't unterstand how use this information (or CCMapClusterAnnotion) to find out the uuid of my BoothAnnotationLocation?

**Comment by choefele** [comment]
When you select an annotation that's controlled by `CCHMapClusterController` on the map, it will be a `CCHMapClusterAnnotation`, not a `BoothAnnotationLocation`. A `CCHMapClusterAnnotation` *contains* an array of `BoothAnnotationLocation`s in the property `annotations`.

Since you are selecting a cluster, I don't see why you need a UUID. You simply have to deal with the array of annotations in the cluster.

**Comment by daclarus** [comment]
>  You simply have to deal with the array of annotations in the cluster.

Oh that's it! :-)

I failed to notice the *array* of `BoothAnnotationLocations` *inside* `CCHMapClusterAnnotation` - silly me.
Thanks for pointing this out to me and thanks again for your help!

**Comment by choefele** [comment]
Welcome – glad you fixed your problem
