### ISSUE TITLE
Assertion when finding an annotation

### ISSUE THREAD

**Issue by emenegro** [choefele/CCHMapClusterController#71]
Hi.

I'm trying to select an annotation previously added to the map using

```- (void)selectAnnotation:(id<MKAnnotation>)annotation andZoomToRegionWithLatitudinalMeters:(CLLocationDistance)latitudinalMeters longitudinalMeters:(CLLocationDistance)longitudinalMeters;```

but the assertion is being fired: **Invalid annotation - can only select annotations previously added by calling addAnnotations:withCompletionHandler:**. I did the adding of the annotations with that method, all my 1242 POIs, the clustering is OK, all my annotations are in the map, etc.

In the previous line of the NSAssert there is the sentence

```BOOL existingAnnotation = [self.annotations containsObject:annotation];```

That ```self.annotations``` only returns a bunch of annotations, not the whole set.

Why is this assertion being raised? Do I have to do something else?

Thank you so much.

**Comment by choefele** [comment]
This might be related to 5681ea9c92d0b2ae972dd83f1d4b2ff2e3dea90d. There was a bug with the implementation of the `annotations` property.

Can you please try using the head revision:

    pod 'CCHMapClusterController', :head

Let me know if this works and I'll cut a new release.

Thanks,
Claus

**Comment by emenegro** [comment]
It works. Thank you so much, @choefele :)

**Comment by choefele** [comment]
Included in release 1.6.6. Thanks for letting me know.
