### ISSUE TITLE
annotation count issue

### ISSUE THREAD

**Issue by vinod1988** [choefele/CCHMapClusterController#73]
Hi 
I have implemented the library in my project, every thing is fine and work well, but i am facing the cluster annotation count issue , The count is not proper. Can you please help me, how to solve this issue, for example i have 50 cluster annotation, first time show cluster count is right, but when we change the our array of data then facing the issue, count not show exact count of my array data apply. So can you please help me.

**Comment by choefele** [comment]
You probably forgot to implement `mapClusterController:willReuseMapClusterAnnotation:`. Please have a look at the example that comes with this repo.

**Comment by choefele** [comment]
Have you found a solution to your problem?

**Comment by vinod1988** [comment]
Hey Thanks Choefele

I have implement the mapClusterController:willReuseMapClusterAnnotation: method but unfortunately inside code commented it. after saw you replay then i have uncomment it. Now every thing is work fine.
