### ISSUE TITLE
Problem removing all annotations

### ISSUE THREAD

**Issue by georgbachmann** [choefele/CCHMapClusterController#78]
Hello,

I have the issue that when I remove all annotations like this

    [self.mapClusterController removeAnnotations:[self.mapClusterController.annotations allObjects]
                           withCompletionHandler:^{
                         ....

It removes the (at least the visible) annotations from the MapView. But as soon as I start zooming out, the annotations that where not visible when removing, are added again?!?
Is this a known issue? Or am I just using the MapClusterController wrong?

What I want to archive is that after the user changes a filter, I'd like to remove all annotations from the map and add the new ones...

**Comment by choefele** [comment]
Hi – I can't reproduce the problem. I modified `resetSettings` from the example app to:

`````Obj-C
- (IBAction)resetSettings
{
    [self.mapClusterControllerRed removeAnnotations:[self.mapClusterControllerRed.annotations allObjects] withCompletionHandler:NULL];
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        self.count = 0;
        Settings *settings = [[Settings alloc] init];
        [self updateWithSettings:settings];
    });
}
````

The above test works as expected.

Are you using 1.6.6? There have been updates to the code for the implementation of the `annotations` property.

**Comment by georgbachmann** [comment]
I was using the latest cocoapods version.
I ended up just throwing away the clustercontroller and instantiating a new one as all the annotations change anyway...

**Comment by sanchofox** [comment]
I have the same problem... On my map I have more than 3000 annotations, but, when I try to remove them all, the most part of the annotations remains on the map... any suggestions?

**Comment by aoptionu** [comment]
Could you please set up a simple sample project that I can use to debug this problem?
