### ISSUE TITLE
clusterisation during setRegion

### ISSUE THREAD

**Issue by lexin** [choefele/CCHMapClusterController#79]
Hello. I have a problem. I have 10 -30 points in one city. When user tap on point

(void)mapView:(MKMapView *)mapView didSelectAnnotationView:(MKAnnotationView *)view 
I call ... [self.mapView setRegion:region animated:YES]; ..

And after this clusterisation works. But every time with different values, because region is different a bit. And this looks not good - after each user's selection clusters are redrawing.
  
but! When user just swipe map regionDidChangeAnimated works too, but clusters are the same!

**Comment by choefele** [comment]
Could you please try out [this recipe](https://github.com/choefele/CCHMapClusterController#centering-the-map-without-changing-the-zoom-level) and see if this helps?

**Comment by lexin** [comment]
Which recipe did you mean?

**Comment by choefele** [comment]
Check the link

**Comment by lexin** [comment]
O_o 
[self.mapView setVisibleMapRect: instead of [self.mapView setRegion works like I want. Thank You!
