### ISSUE TITLE
Annotations are not visible if removed and added back again

### ISSUE THREAD

**Issue by uwinkler** [choefele/CCHMapClusterController#86]
Cluster annotations and normal annotations are not visible if one removes all annotations and than adds them back again to the mapview.

You can reproduce this behaviour using the TSCClusterMapViewDemo app

Step 1: press  +All to add all public bathrooms. The cluster annotation will appear
Step 2: press  -All to remove all  annotations.
Step 3: press +All again. No cluster annotation will be visible. You have to scroll or zoom the map to force the annotations to appear

![screen shot 2015-04-23 at 09 16 34](https://cloud.githubusercontent.com/assets/582533/7292160/92c62dc4-e999-11e4-8551-4de57a310769.png)

**Comment by choefele** [comment]
Where is the source code to the TSCClusterMapViewDemo app that you mentioned?

**Comment by uwinkler** [comment]
Sorry - my bad :(  That issue should go to TSClusterMapView project.
