### ISSUE TITLE
Annotations move freely in the view when user rotates view.

### ISSUE THREAD

**Issue by emkou** [choefele/CCHMapClusterController#88]
Hello, 

I am facing a problem with unique and clustered annotations where the user rotates the view and the annotations move (a bit) around and close to the annotation frame, they are not exactly positioned at one place, so the pin base moves visibly. Is there any way to disable this behaviour?

**Comment by choefele** [comment]
Can you provide a sample project for this issue? When using the sample app in this repo, rotating the app to landscape and back doesn't change the clusters. What's the difference to your setup?

**Comment by emkou** [comment]
No problem, will separate some code as soon as possible in sample project and send here.
