### ISSUE TITLE
Crash on [CCHMapClusterController mapView:regionDidChangeAnimated:]_block_invoke

### ISSUE THREAD

**Issue by kuoliangkwong** [choefele/CCHMapClusterController#89]
Hi we hit an error saying the following error:

[CCHMapClusterController mapView:regionDidChangeAnimated:]_block_invoke (CCHMapClusterController.m:296)
2	libdispatch.dylib 0x36b432e3 _dispatch_call_block_and_release + 8
3	libdispatch.dylib 0x36b432cf _dispatch_client_callout + 20
4	libdispatch.dylib 0x36b46d2f _dispatch_main_queue_callback_4CF + 1328
5	CoreFoundation 0x282ec609 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 6
6	CoreFoundation 0x282ead09 __CFRunLoopRun + 1510
7	CoreFoundation 0x28237201 CFRunLoopRunSpecific + 474
8	CoreFoundation 0x28237013 CFRunLoopRunInMode + 104
9	GraphicsServices 0x2fb16201 GSEventRunModal + 134
10	UIKit 0x2b9dba59 UIApplicationMain + 1438

We are unable to reproduce it. It seems like an error happens in real time.

**Comment by choefele** [comment]
Closing this for now. Please reopen if there are new ideas on how to reproduce this issue. Thanks
