### ISSUE TITLE
Get the original annotation

### ISSUE THREAD

**Issue by cikpis** [choefele/CCHMapClusterController#90]
Hi there, first of all thanks for your work! It's pretty awesome ;)

I'm here just because I'm wondering if I can use this project because after have read the code it seems there is no way to get the original annotation in CCHMapClusterAnnotation. Am I right?

The problem in a few word is how to get one or more custom properties inside my original annotation in "mapView:viewForAnnotation:"?

Thanks in advance, 
Cheers!

Carmelo

**Comment by choefele** [comment]
In `mapView:viewForAnnotation`, you will receive an instance of `CCHMapClusterAnnotation`. This class has a property `annotations`, that contains your annotation instances. See [this code](https://github.com/choefele/CCHMapClusterController/blob/master/CCHMapClusterController%20Example%20iOS/CCHMapClusterController%20Example%20iOS/MapViewController.m#L185) for an example of how to use `CCHMapClusterAnnotation`.

**Comment by cikpis** [comment]
Ohh I see. I was blinded of "annotations" like an array. I didn't think it has even one annotation.

Thanks for your time,
cheers!

Carmelo
