### ISSUE TITLE
mapView:regionDidChangeAnimated:

### ISSUE THREAD

**Issue by cikpis** [choefele/CCHMapClusterController#91]
Hi there again! Thanks for your previous answer.

Anyway, I'm facing now another problem. I followed your code in roder to avoid that "mapView:regionDidChangeAnimated:" is called after "mapview:didSelectAnnotationView:" but it is called anyway.

Here the code:
```javascript
    func mapView(mapView: MKMapView!, didSelectAnnotationView view: MKAnnotationView!) {
        
        var mapPointForCoordinate = MKMapPointForCoordinate(view.annotation.coordinate)
        var visibleMapRect = mapView.visibleMapRect
        visibleMapRect.origin.x = mapPointForCoordinate.x - visibleMapRect.size.width * 0.5
        visibleMapRect.origin.y = mapPointForCoordinate.y - visibleMapRect.size.height * 0.5
        mapView.setVisibleMapRect(visibleMapRect, animated: true)
        
        var transform = CGAffineTransformScale(CGAffineTransformIdentity, 2.0, 2.0)

        UIView.animateWithDuration(
            0.2,
            animations: { () -> Void in
                view.transform = transform
            })
    }
    
    func mapView(mapView: MKMapView!, didDeselectAnnotationView view: MKAnnotationView!) {
        
        var transform = CGAffineTransformScale(CGAffineTransformIdentity, 1.0, 1.0)
        
        UIView.animateWithDuration(
            0.2,
            animations: { () -> Void in
                view.transform = transform
            })
    }
```

So, do you why after select an annotationView the "mapView:regionDidChangeAnimated:" is called anyway?

Thanks in advance,
cheers!

Carmelo

**Comment by cikpis** [comment]
Also the "mapVIew:didDeselectAnnotationView:" is called due to "mapView:regionDidChangeAnimated:" in your side is called.

Carmelo

**Comment by choefele** [comment]
I'm not sure what you are trying to achieve. Does [this code recipe](https://github.com/choefele/CCHMapClusterController#receiving-taps-on-annotation-views) help?

**Comment by cikpis** [comment]
If you look at the code that is exactly what I'm doing.

**Comment by cikpis** [comment]
Basically if you zoom the map to the max available zoom and then call "setVisibleMapRect", the "mapVIew:didDeselectAnnotationView:" is called due to "mapView:regionDidChangeAnimated:" in your side is called. Is it clear now?.

**Comment by choefele** [comment]
Sorry, but what exactly is the question you are asking?

**Comment by cikpis** [comment]
the recipe you wrote works only if you use it on normal zoom. If you try to use it after user has zoomed to the max level, you'll see the map does a back zoom and then move to the center. 

So my question is: there is some way to avoid your code call "mapVIew:didDeselectAnnotationView:" after that automatically zoom out?

**Comment by choefele** [comment]
This zoom is done by MapKit and automatically triggers `mapView:regionDidChangeAnimated:`. When the map view region changes, this will automatically [deselect the current annotation view](https://github.com/choefele/CCHMapClusterController/blob/master/CCHMapClusterController/CCHMapClusterController.m#L289).

This issues is discussed in #65. Still unsure on how to handle this. Maybe it's best to simply remove the call to `deselectAllAnnotations` and everyone can implement his/her own deselection code.

**Comment by cikpis** [comment]
Maybe you can add a delegate about that like this:

```javascript
-(BOOL)canDeselectAnnotations {
   return YES;
}
```
