### ISSUE TITLE
Customisation of annotation view

### ISSUE THREAD

**Issue by nWorksTechnologies** [choefele/CCHMapClusterController#93]
Using the CCHMapClusterController I can change the image name for image property of class "ClusterAnnotationView". But I want a customise pin with more than one image on the annotation view. I have done it by adding subview on annotation view in the class "ClusterAnnotationView" (method : - (void)layoutSubviews) . But app crashes when the annotations get refreshed due to dragging or zooming in/out on map.

**Comment by choefele** [comment]
You can use [this code](https://github.com/Stolpersteine/stolpersteine-ios/blob/master/Stolpersteine/iPhone/MapClusterAnnotationView.m) as an example for this kind of customization. `MapClusterAnnotationView` shows different images depending on the number of items in the cluster and also contains a `UILabel` as subview. See also the calls to `mapClusterAnnotationView.oneLocation` in [this class](https://github.com/Stolpersteine/stolpersteine-ios/blob/master/Stolpersteine/iPhone/MapViewController.m), which switch the look of `MapClusterAnnotationView`.

**Comment by nWorksTechnologies** [comment]
Working!!! Thanks a lot.
