### ISSUE TITLE
Zoom map

### ISSUE THREAD

**Issue by matrosovDev** [choefele/CCHMapClusterController#94]
Hi! Great library, I have a question, for example if the map display "80" pins in some region, by pressing on pin that says "80" I want to zoom my map. If I zoom a map I just want to shaw callout view.

**Comment by choefele** [comment]
Perhaps [this code snippet](https://github.com/choefele/CCHMapClusterController#zooming-in-to-a-cluster) helps?

**Comment by choefele** [comment]
I'm closing this issue because I haven't heard back from you in a while and I assume your problem is solved. Thanks
