### ISSUE TITLE
clusterAnnotationsForMapView crash with iPhone 6

### ISSUE THREAD

**Issue by hirenj102** [choefele/CCHMapClusterController#96]
Hello,

I have a iphone 6 and i check with this code for click on cluster pin to show annotation.it's working in iPhone 4s but not working iPhone 6.i have check with Xcode crash report than found a one crash for below line of code

 [(REVClusterBlock *)[clusteredBlocks objectAtIndex:localTileNumber] addAnnotation:pin];

Please advice how to solve this issue.

**Comment by choefele** [comment]
I'm not aware of any crashes in this library. Can you please attach a sample project that reproduces this issue.

Thanks

**Comment by choefele** [comment]
Haven't heard back for this issue in a while – I assume it has been solved.
